Add NTStatus errors
microsoft/go-crypto-winnative pull request #79
Opened 2024-12-18 00:44 UTC by mertakman

This PR adds NTStatus errors to the bcrypt package and updates the bcrypt function signatures to implement NTStatus.
Also contains a little patch cmd/mksyscall to truncate the windows package import for NTStatus.
Fixes: #68

2024-12-18 07:26 UTC, qmuntal requested changes
Cool! Just one comment: you should add a test to the `cng` package which checks that a returned error does contain a human friendly error message rather than a hex code.

2024-12-18 07:26 UTC, qmuntal commented on internal/bcrypt/ntstatus.go
> +//sys	FormatMessage(flags uint32, msgsrc uintptr, msgid uint32, langid uint32, buf []uint16, args *byte) (n uint32, err error) = FormatMessageW
Make `FormatMessage` unexported.

2024-12-18 14:36 UTC, qmuntal approved these changes
LGTM!

2024-12-20 09:25 UTC, gdams approved these changes

2024-12-20 09:53 UTC, merged